### ISSUE TITLE
🎉[FEAT] : 주차장 목록 (거리 미포함) 불러오는 기능 추가

### ISSUE THREAD

**Issue by PKafka0320** [softeerbootcamp-3nd/I-Atcha-BE#23]
# Description
거리를 포함하지 않는 주차장 목록을 불러올 수 있도록 한다.

# To-do
- [x] 거리를 포함해서 반환하는 기능의 URI 수정
- [x] 거리를 미포함해서 반환하는 기능의 URI 추가
- [x] 주차장 목록 DTO 수정
- [x] 위치 파라미터 없이 주차장 목록을 불러오는 함수 추가
