### ISSUE TITLE
🎉FEAT 주차 요금 계산 기능

### ISSUE THREAD

**Issue by Yang-soeun** [softeerbootcamp-3nd/I-Atcha-BE#25]
## To-Do

- [x] 데이터베이스 수정
- [x] 기존 로직 데베 변경된 부분 수정
- [x] 주차 요금 기능 계산 개발
- [x] 메모 테이블 없는 로직으로 수정
