### ISSUE TITLE
🛠[FIX] : 주차시간이 제대로 시작하지 않는 문제

### ISSUE THREAD

**Issue by Win-9** [softeerbootcamp-3nd/I-Atcha-BE#44]
### Todo
- [x] 고정된 DB의 Start시간 변경
- [x] 사용자에 주차시간 칼럼 추가
- [x] 서버 실행시가 아닌 주차 시작시 주차시간 업데이트
- [x] 주차 종료 시 0시가 되도록 수정
- [x] 로직변경
